image:
  file: .cde.Dockerfile

tasks:
  - name: Terraform
    command: |
      gp sync-await waitonazurecli
      cde/terraform.sh
  - name: Azure CLI
    command: |
      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      az account set --subscription "$ARM_SUBSCRIPTION_NAME"
      az account show
      gp sync-done waitonazurecli

vscode:
  extensions:
    - hashicorp.terraform