image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terraform
    command: |
      cd  terraform
      terraform init
      terraform fmt
      gp sync-await waitonazurecli
      terraform validate
      terraform plan
  - name: Azure CLI
    command: |
      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      az account set --subscription "$ARM_SUBSCRIPTION_NAME"
      az account show
      gp sync-done waitonazurecli

vscode:
  extensions:
    - hashicorp.terraform