image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terraform
    command: |
      cd  terraform
      terraform init
      terraform fmt
      gp sync-await waitonazurecli
      terraform validate
      terraform plan
  - name: Azure CLI
    command: |
      az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      az account set --subscription "$AZURE_SUBSCRIPTION"
      az account show
      gp sync-done waitonazurecli

vscode:
  extensions:
    - hashicorp.terraform