image:
  file: .cde.Dockerfile

tasks:
  - name: Terraform
    command: |
      gp sync-await waitonazurecli
      sh ./cde/terraform.sh
  - name: Azure CLI
    command: |
      sh ./cde/azure.sh
      gp sync-done waitonazurecli

vscode:
  extensions:
    - hashicorp.terraform