name: 'Terraform'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: 'Terraform Format'
        working-directory: terraform
        run: terraform fmt -check

      - name: 'Terraform Init'
        working-directory: terraform
        run: terraform init -backend-config="storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT" -backend-config="container_name=$TF_BACKEND_CONTAINER" -backend-config="key=template.azure.terraform.tfstate"

      - name: 'Terraform Validate'
        working-directory: terraform
        run: terraform validate

      - name: 'Terraform Plan'
        working-directory: terraform    
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve