name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-dev:
    uses: ./.github/workflows/job.yml
    with:
      UNIQUE_NAMESPACE: ${{ vars.UNIQUE_NAMESPACE }}
      ORGANISATION: ${{ vars.ORGANISATION }}
      ARM_REGION: ${{ vars.ARM_REGION }}
      ENVIRONMENT: "development"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}